import { grayColors, saColors } from "./colors";
import { saRadius } from "./radius";
import { fontFamilies } from "./typography";

const shadow = {
  sm: {
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  md: {
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 4,
  },
  heroCard: {
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.25,
    shadowRadius: 24,
    elevation: 8,
  },
} as const;

export const componentTokens = {
  button: {
    radius: saRadius.md,
    minHeight: 48,
    paddingX: 14,
    paddingY: 10,
    font: {
      family: fontFamilies.sans.native.medium,
      size: 14,
      lineHeight: 20,
    },
    variants: {
      default: {
        background: "#ffffff",
        border: grayColors["400"],
        text: grayColors["700"],
        pressedBackground: grayColors["500"],
        pressedBorder: grayColors["500"],
        pressedText: "#ffffff",
      },
      cta: {
        background: saColors.primary,
        border: saColors.primary,
        text: "#ffffff",
        pressedBackground: saColors.dark,
        pressedBorder: saColors.dark,
        pressedText: "#ffffff",
      },
      secondary: {
        background: saColors.blue,
        border: saColors.blue,
        text: "#ffffff",
        pressedBackground: saColors.blue,
        pressedBorder: saColors.blue,
        pressedText: "#ffffff",
      },
      tertiary: {
        background: "transparent",
        border: "transparent",
        text: saColors.primary,
        pressedBackground: "transparent",
        pressedBorder: "transparent",
        pressedText: saColors.dark,
      },
      disabled: {
        background: grayColors["300"],
        border: grayColors["300"],
        text: grayColors["500"],
      },
    },
  },
  breadcrumb: {
    fontSize: 12,
    lineHeight: 20,
    fontFamily: fontFamilies.sans.native.medium,
    gradientWidth: 48,
    itemColor: grayColors["700"],
    currentColor: grayColors["500"],
    whiteItemColor: "#ffffff",
    whiteCurrentColor: "rgba(255,255,255,0.7)",
    separatorColor: grayColors["500"],
    whiteSeparatorColor: "rgba(255,255,255,0.5)",
    grayGradientColor: grayColors["50"],
    whiteGradientColor: "#ffffff",
  },
  card: {
    background: "#ffffff",
    border: grayColors["200"],
    radius: saRadius.md,
    padding: 24,
    shadow: shadow.sm,
    shadowLg: shadow.md,
  },
  input: {
    minHeight: 40,
    radius: saRadius.md,
    border: grayColors["200"],
    borderFocus: saColors.primary,
    placeholder: grayColors["500"],
    text: grayColors["900"],
    paddingX: 12,
    paddingY: 8,
  },
  sheet: {
    backdropColor: "rgba(0,0,0,0.6)",
    handleColor: grayColors["300"],
    handleHeight: 6,
    handleWidth: 48,
    contentRadiusTop: 24,
    insetX: 16,
  },
  calendar: {
    daySize: 32,
    dayRadius: saRadius.md,
    selectedBackground: saColors.blue,
    selectedText: "#ffffff",
    todayBackground: grayColors["100"],
    todayText: grayColors["900"],
    text: grayColors["700"],
    mutedText: grayColors["500"],
    navigationBorder: grayColors["200"],
    navigationIcon: grayColors["900"],
  },
  transportHero: {
    background: saColors.blue,
    accent: saColors.medium,
    badgeBackground: "rgba(255,255,255,0.14)",
    badgeBorder: "rgba(255,255,255,0.34)",
    overlay: [
      "rgba(0, 47, 73, 0.96)",
      "rgba(0, 47, 73, 0.74)",
      "rgba(0, 47, 73, 0.42)",
    ],
    paddingX: 20,
    paddingTop: 32,
    paddingBottom: 32,
    title: {
      fontFamily: fontFamilies.sans.native.bold,
      fontSize: 28,
      lineHeight: 31,
      color: "#ffffff",
    },
    subtitle: {
      fontFamily: fontFamilies.sans.native.semibold,
      fontSize: 18,
      lineHeight: 29,
      color: "rgba(255,255,255,0.85)",
    },
    searchCard: {
      background: "#ffffff",
      radius: 24,
      padding: 16,
      border: "rgba(0,0,0,0.05)",
      shadow: shadow.heroCard,
    },
    searchField: {
      radius: saRadius.md,
      border: grayColors["300"],
      divider: grayColors["200"],
      placeholder: grayColors["500"],
      icon: "#000000",
      rowHeight: 52,
    },
    uspCard: {
      background: "rgba(255,255,255,0.06)",
      border: "rgba(255,255,255,0.14)",
      iconBackground: "rgba(255,255,255,0.14)",
      radius: 16,
      padding: 12,
    },
    partnerStrip: {
      background: "#ffffff",
      border: grayColors["200"],
      label: grayColors["600"],
    },
  },
} as const;

export type ComponentTokens = typeof componentTokens;
