import { grayColors, saColors } from './colors';
import { saRadius } from './radius';
import { fontFamilies } from './typography';

const shadow = {
  sm: {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  md: {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 4,
  },
  heroCard: {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.25,
    shadowRadius: 24,
    elevation: 8,
  },
} as const;

export const componentTokens = {
  button: {
    radius: saRadius.md,
    minHeight: 48,
    paddingX: 14,
    paddingY: 10,
    font: {
      family: fontFamilies.sans.native.medium,
      size: 14,
      lineHeight: 20,
    },
    variants: {
      default: {
        background: '#ffffff',
        border: grayColors['400'],
        text: grayColors['700'],
        pressedBackground: grayColors['500'],
        pressedBorder: grayColors['500'],
        pressedText: '#ffffff',
      },
      cta: {
        background: saColors.primary,
        border: saColors.primary,
        text: '#ffffff',
        pressedBackground: saColors.dark,
        pressedBorder: saColors.dark,
        pressedText: '#ffffff',
      },
      secondary: {
        background: saColors.blue,
        border: saColors.blue,
        text: '#ffffff',
        pressedBackground: saColors.blue,
        pressedBorder: saColors.blue,
        pressedText: '#ffffff',
      },
      tertiary: {
        background: 'transparent',
        border: 'transparent',
        text: saColors.primary,
        pressedBackground: 'transparent',
        pressedBorder: 'transparent',
        pressedText: saColors.dark,
      },
      disabled: {
        background: grayColors['300'],
        border: grayColors['300'],
        text: grayColors['500'],
      },
    },
  },
  breadcrumb: {
    fontSize: 12,
    lineHeight: 20,
    fontFamily: fontFamilies.sans.native.medium,
    gradientWidth: 48,
    itemColor: grayColors['700'],
    currentColor: grayColors['500'],
    whiteItemColor: '#ffffff',
    whiteCurrentColor: 'rgba(255,255,255,0.7)',
    separatorColor: grayColors['500'],
    whiteSeparatorColor: 'rgba(255,255,255,0.5)',
    grayGradientColor: grayColors['50'],
    whiteGradientColor: '#ffffff',
  },
  card: {
    background: '#ffffff',
    border: grayColors['200'],
    radius: saRadius.md,
    padding: 24,
    shadow: shadow.sm,
    shadowLg: shadow.md,
  },
  bookingFlow: {
    screen: {
      background: saColors.bg,
      contentPadding: 16,
      contentPaddingBottom: 24,
      sectionGap: 24,
      sectionGapLarge: 32,
    },
    card: {
      background: '#ffffff',
      border: grayColors['200'],
      selectedBorder: saColors.primary,
      borderWidth: 1,
      radius: saRadius.lg,
      padding: 16,
      compactPadding: 12,
      shadow: shadow.sm,
    },
    divider: {
      color: grayColors['200'],
      height: 1,
      marginY: 12,
    },
    typography: {
      stepTitle: {
        fontSize: 20,
        lineHeight: 28,
      },
      summaryTitle: {
        fontSize: 16,
        lineHeight: 24,
      },
      participantTitle: {
        fontSize: 16,
        lineHeight: 24,
      },
      body: {
        fontSize: 14,
        lineHeight: 20,
      },
      price: {
        fontSize: 18,
        lineHeight: 18,
      },
    },
    text: {
      primary: '#000000',
      body: grayColors['700'],
      muted: grayColors['500'],
      price: '#000000',
    },
    activitySummary: {
      marginBottom: 24,
      ratingGap: 6,
      participantGap: 12,
      participantMarginTop: 16,
      iconSize: 16,
      editIconSize: 18,
      shadow: shadow.md,
    },
    radio: {
      size: 20,
      innerSize: 14,
      borderWidth: 1,
      innerBorderWidth: 2,
      border: grayColors['500'],
      selected: saColors.primary,
      background: '#ffffff',
    },
    stepper: {
      buttonSize: 36,
      amountMinWidth: 20,
      gap: 12,
      border: grayColors['200'],
      icon: grayColors['500'],
      disabledIcon: grayColors['300'],
      background: '#ffffff',
    },
    discountPill: {
      radius: saRadius.xl,
      paddingX: 12,
      paddingY: 8,
      border: grayColors['200'],
      selectedBorder: saColors.primary,
      background: '#ffffff',
      selectedBackground: 'rgba(255, 56, 92, 0.08)',
    },
    availabilitySelect: {
      background: '#ffffff',
      border: grayColors['200'],
      selectedBorder: '#16a34a',
      radius: saRadius.md,
      paddingX: 16,
      paddingY: 12,
      minHeight: 48,
      iconSize: 32,
      iconRadius: saRadius.md,
      iconBackground: '#16a34a',
      iconColor: '#ffffff',
      chevronColor: grayColors['500'],
      menuBackground: '#ffffff',
      menuBorder: grayColors['200'],
      menuText: '#000000',
      menuMuted: grayColors['500'],
      menuRadius: saRadius.md,
      menuShadow: shadow.sm,
      menuPaddingY: 10,
      optionSelectedBackground: grayColors['50'],
      optionPaddingX: 16,
      optionPaddingY: 10,
    },
    footer: {
      background: '#ffffff',
      border: grayColors['200'],
      paddingX: 16,
      paddingY: 12,
    },
  },
  activityDetail: {
    screen: {
      background: saColors.bg,
      contentPaddingX: 16,
      sectionGap: 24,
      sectionGapLarge: 32,
    },
    hero: {
      aspectRatio: 4 / 3,
      indicatorActiveColor: '#ffffff',
      indicatorInactiveColor: 'rgba(255,255,255,0.4)',
      gradientStart: 'rgba(0,0,0,0)',
      gradientEnd: 'rgba(0,0,0,0.35)',
      overlayPaddingX: 16,
      overlayPaddingY: 12,
    },
    shortDescription: {
      paddingTop: 16,
      titleMarginBottom: 8,
      metaGap: 8,
      ratingGap: 4,
    },
    uspChip: {
      background: '#ffffff',
      border: grayColors['200'],
      radius: saRadius.xl,
      paddingX: 12,
      paddingY: 8,
      iconSize: 16,
      gap: 6,
    },
    section: {
      titleFontSize: 18,
      titleLineHeight: 25,
      titleMarginBottom: 12,
      gap: 24,
    },
    reviewCard: {
      background: '#ffffff',
      border: grayColors['200'],
      radius: saRadius.md,
      padding: 16,
      gap: 8,
      starColor: saColors.primary,
      starSize: 14,
    },
    similar: {
      gap: 12,
      itemWidth: 220,
    },
    ctaBar: {
      background: '#ffffff',
      borderTop: grayColors['200'],
      paddingX: 16,
      paddingY: 12,
      pricePillBackground: saColors.light,
      pricePillRadius: saRadius.md,
      pricePillPaddingX: 12,
      pricePillPaddingY: 6,
      shadow: shadow.md,
    },
    iconButton: {
      size: 40,
      radius: 999,
      background: 'rgba(255,255,255,0.92)',
      pressedBackground: '#ffffff',
      iconSize: 20,
      iconColor: grayColors['900'],
    },
  },
  discoverHome: {
    screen: {
      background: saColors.bg,
      contentPaddingX: 16,
      sectionGap: 32,
    },
    section: {
      headerPaddingX: 16,
      headerMarginBottom: 12,
      titleFontSize: 20,
      titleLineHeight: 28,
      subtitleFontSize: 14,
      subtitleLineHeight: 20,
      subtitleColor: grayColors['600'],
    },
    greeting: {
      paddingX: 16,
      paddingY: 16,
      titleFontSize: 24,
      titleLineHeight: 32,
      bodyFontSize: 14,
      bodyLineHeight: 20,
      bodyColor: grayColors['600'],
    },
    weather: {
      paddingX: 16,
      paddingY: 12,
      iconSize: 32,
      temperatureFontSize: 24,
      temperatureLineHeight: 32,
      labelColor: grayColors['600'],
    },
    chip: {
      background: '#ffffff',
      activeBackground: grayColors['900'],
      border: grayColors['200'],
      activeBorder: grayColors['900'],
      text: grayColors['700'],
      activeText: '#ffffff',
      radius: saRadius.xl,
      paddingX: 14,
      paddingY: 8,
      gap: 8,
    },
    carousel: {
      itemGap: 12,
      itemWidth: 280,
      contentInsetStart: 16,
      contentInsetEnd: 16,
    },
    mapPreview: {
      background: '#ffffff',
      radius: saRadius.lg,
      borderColor: grayColors['200'],
      height: 220,
      previewOverlay: 'rgba(0,0,0,0.05)',
    },
    pullToRefresh: {
      tintColor: saColors.primary,
    },
  },
  searchResults: {
    bar: {
      background: '#ffffff',
      border: grayColors['200'],
      radius: saRadius.lg,
      paddingX: 12,
      paddingY: 10,
      iconColor: grayColors['500'],
      placeholderColor: grayColors['400'],
      textColor: grayColors['900'],
      gap: 8,
      shadow: shadow.sm,
    },
    suggest: {
      background: '#ffffff',
      border: grayColors['200'],
      radius: saRadius.md,
      itemPaddingX: 16,
      itemPaddingY: 12,
      itemDividerColor: grayColors['100'],
      iconColor: grayColors['500'],
      textColor: grayColors['900'],
      mutedColor: grayColors['500'],
      shadow: shadow.md,
    },
    facetChip: {
      background: '#ffffff',
      activeBackground: grayColors['900'],
      border: grayColors['200'],
      activeBorder: grayColors['900'],
      text: grayColors['700'],
      activeText: '#ffffff',
      countColor: grayColors['500'],
      radius: saRadius.xl,
      paddingX: 12,
      paddingY: 6,
      gap: 6,
    },
    sortPicker: {
      background: '#ffffff',
      border: grayColors['200'],
      radius: saRadius.md,
      paddingX: 12,
      paddingY: 8,
      iconColor: grayColors['700'],
      textColor: grayColors['900'],
    },
    resultCard: {
      background: '#ffffff',
      radius: saRadius.lg,
      border: grayColors['200'],
      padding: 12,
      gap: 12,
      shadow: shadow.sm,
      imageAspectRatio: 4 / 3,
      titleFontSize: 16,
      titleLineHeight: 22,
      metaFontSize: 13,
      metaLineHeight: 18,
      metaColor: grayColors['600'],
    },
    empty: {
      paddingX: 24,
      paddingY: 48,
      iconColor: grayColors['400'],
      titleColor: grayColors['900'],
      bodyColor: grayColors['600'],
    },
  },
  formField: {
    gap: 6,
    labelColor: grayColors['700'],
    labelFontSize: 13,
    labelLineHeight: 18,
    hintColor: grayColors['500'],
    hintFontSize: 12,
    hintLineHeight: 16,
    errorColor: '#dc2626',
    errorFontSize: 12,
    errorLineHeight: 16,
    requiredColor: '#dc2626',
    asteriskGap: 2,
  },
  tabBar: {
    background: '#ffffff',
    borderTop: grayColors['200'],
    paddingX: 8,
    paddingY: 8,
    iconSize: 24,
    iconActive: saColors.blue,
    iconInactive: grayColors['500'],
    labelFontSize: 10,
    labelLineHeight: 14,
    labelMarginTop: 2,
    labelActive: saColors.blue,
    labelInactive: grayColors['500'],
    indicatorColor: saColors.primary,
    indicatorHeight: 2,
    shadow: shadow.sm,
  },
  header: {
    background: '#ffffff',
    border: grayColors['200'],
    paddingX: 16,
    paddingY: 12,
    height: 56,
    titleFontSize: 17,
    titleLineHeight: 22,
    titleColor: grayColors['900'],
    iconColor: grayColors['900'],
    iconSize: 24,
    backIconSize: 28,
    actionGap: 16,
    transparentBackground: 'transparent',
    blurOverlay: 'rgba(255,255,255,0.92)',
  },
  input: {
    minHeight: 40,
    radius: saRadius.md,
    border: grayColors['200'],
    borderFocus: saColors.primary,
    placeholder: grayColors['500'],
    text: grayColors['900'],
    paddingX: 12,
    paddingY: 8,
  },
  sheet: {
    backdropColor: 'rgba(0,0,0,0.6)',
    handleColor: grayColors['300'],
    handleHeight: 6,
    handleWidth: 48,
    contentRadiusTop: 24,
    insetX: 16,
  },
  calendar: {
    daySize: 32,
    dayRadius: saRadius.md,
    selectedBackground: saColors.blue,
    selectedText: '#ffffff',
    todayBackground: grayColors['100'],
    todayText: grayColors['900'],
    text: grayColors['700'],
    mutedText: grayColors['500'],
    navigationBorder: grayColors['200'],
    navigationIcon: grayColors['900'],
    availability: {
      containerBorder: grayColors['200'],
      headerBackground: '#ffffff',
      headerHeight: 48,
      navigationCellWidth: 48,
      navigationIconSize: 20,
      monthFontSize: 16,
      monthLineHeight: 22,
      weekdayHeight: 28,
      weekdayFontSize: 11,
      weekdayLineHeight: 16,
      dayHeight: 44,
      dayRadius: saRadius.md,
      dayGap: 3,
      dayFontSize: 16,
      dayLineHeight: 19,
      priceFontSize: 9,
      priceLineHeight: 11,
      weekdayText: grayColors['900'],
      availableBackground: '#a7f3cf',
      selectedBackground: saColors.primary,
      selectedText: '#ffffff',
      text: grayColors['900'],
      mutedText: grayColors['400'],
      priceText: grayColors['600'],
      selectedPriceText: 'rgba(255,255,255,0.82)',
      unavailableBackground: 'transparent',
      modal: {
        contentGap: 20,
        contentPaddingX: 18,
        contentPaddingTop: 4,
        contentPaddingBottom: 18,
        summaryPadding: 16,
        summaryTitleFontSize: 16,
        summaryTitleLineHeight: 23,
        summaryMetaFontSize: 14,
        summaryMetaLineHeight: 20,
        summaryStarFontSize: 18,
        summaryStarLineHeight: 20,
        headingFontSize: 24,
        headingLineHeight: 31,
        headingMarginBottom: 16,
      },
    },
  },
  transportHero: {
    background: saColors.blue,
    accent: saColors.medium,
    badgeBackground: 'rgba(255,255,255,0.14)',
    badgeBorder: 'rgba(255,255,255,0.34)',
    overlay: [
      'rgba(0, 47, 73, 0.96)',
      'rgba(0, 47, 73, 0.74)',
      'rgba(0, 47, 73, 0.42)',
    ],
    paddingX: 20,
    paddingTop: 32,
    paddingBottom: 32,
    title: {
      fontFamily: fontFamilies.sans.native.bold,
      fontSize: 28,
      lineHeight: 31,
      color: '#ffffff',
    },
    subtitle: {
      fontFamily: fontFamilies.sans.native.semibold,
      fontSize: 18,
      lineHeight: 29,
      color: 'rgba(255,255,255,0.85)',
    },
    searchCard: {
      background: '#ffffff',
      radius: 24,
      padding: 16,
      border: 'rgba(0,0,0,0.05)',
      shadow: shadow.heroCard,
    },
    searchField: {
      radius: saRadius.md,
      border: grayColors['300'],
      divider: grayColors['200'],
      placeholder: grayColors['500'],
      icon: '#000000',
      rowHeight: 52,
    },
    uspCard: {
      background: 'rgba(255,255,255,0.06)',
      border: 'rgba(255,255,255,0.14)',
      iconBackground: 'rgba(255,255,255,0.14)',
      radius: 16,
      padding: 12,
    },
    partnerStrip: {
      background: '#ffffff',
      border: grayColors['200'],
      label: grayColors['600'],
    },
  },
} as const;

export type ComponentTokens = typeof componentTokens;
